-- Adds a short 6-char alphanumeric identifier to proposals for compact URLs.
-- Existing proposals keep short_id='' and continue to be addressable by UUID
-- only. New proposals get a unique short_id generated by the backend.
ALTER TABLE gonka_vote.proposals
    ADD COLUMN IF NOT EXISTS short_id String DEFAULT '';
